apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "mychart.name" . }}
    helm.sh/chart: {{ include "mychart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.service.path }}
        backend:
          serviceName: {{ include "mychart.fullname" . }}-svc
          servicePort: {{ .Values.service.port }}
