replicaCount: 2

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

envvars:
  env: dev

nameOverride: "caylent-dev"
fullnameOverride: "caylent-dev"

service:
  type: ClusterIP
  port: 80
