version: 2
jobs:
  build-image:
    docker:
      #- image: ubuntu:18.04
      - image: docker:stable-dind

        environment:
          TEST_VAR: test
    steps:
      - checkout
      - run:
          name: Update packages
          command: |
            pwd
            ls
          # name: Install dependencies
          # command: |
          #   pwd


  # test:
  #   docker:
  #     - image: circleci/<language>:<version TAG>
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
