version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: |
         cd docker/nginx-hello/
         docker build --no-cache -t custom-nginx:latest .

     # deploy the image
     - run: |
         docker tag custom-nginx ddedamian/custom-nginx:latest
         docker push ddedamian/custom-nginx:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
