version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
        environment:
          TEST_VAR: test
    steps:
      - checkout
      - run:
          name: Update packages
          command: |
            apt update
            apt upgrade -y


  # test:
  #   docker:
  #     - image: circleci/<language>:<version TAG>
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
