version: 2
jobs:
 build-image:
   machine: true
   steps:
     - checkout
     # login into dockerHub
     - run: |
         cd docker/nginx-hello/
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker build --no-cache -t custom-nginx:latest .
         docker tag custom-nginx ddedamian/custom-nginx:latest
         docker push ddedamian/custom-nginx:latest


workflows:
  version: 2
  build_and_test:
    jobs:
      - build-image
      # - test
