replicaCount: 2

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

envvars:
  env: stage

nameOverride: "caylent-stage"
fullnameOverride: "caylent-stage"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
    - chart-example.stage
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
