replicaCount: 2

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

envvars:
  env: stage

nameOverride: "caylent-stage"
fullnameOverride: "caylent-stage"

service:
  type: LoadBalancer
  port: 80
