replicaCount: 2

image:
  repository: ddedamian/custom-nginx
  tag: test
  pullPolicy: IfNotPresent

envvars:
  env: development

nameOverride: "caylent-dev"
fullnameOverride: "caylent-dev"

service:
  type: LoadBalancer
  # type: ClusterIp # In case you want to deploy it on locally
  port: 80
  path: dev
