environments:
  stage:
  dev:

releases:
- name: custom-nginx-{{ .Environment.Name }}
  namespace: caylent-{{ .Environment.Name }}
  chart: ./charts/custom-nginx-caylent
  values:
    - ./env_vars/{{ .Environment.Name }}/values.yaml
    - ./env_vars/{{ .Environment.Name }}/secrets.yaml.dec
